apiVersion: v1
kind: Service
metadata:
  name: spendlytic-backend-service
spec:
  selector:
    app: spendlytic-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer 